# Generated by Django 3.2.10 on 2021-12-18 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=24)),
                ('title', models.CharField(max_length=24)),
                ('description', models.TextField()),
                ('start_date_time', models.DateField(null=True)),
                ('end_date_time', models.DateField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'tour',
            },
        ),
    ]
